Update app-scripts.md
hackforla/tables pull request #82
Opened 2024-09-11 21:50 UTC by wesley115

Fixes #74 & Fixes #51

update scripts info for 
-AuditGoogleDrivesPermission
-GoogleformTimeTrigger
-GoogleformTimeTrigger_Copy-for_2_form

2024-09-25 00:32 UTC, Reltre commented
@wesley115 Do we have any execution log data for `AuditGoogleDrivesPermission` and `GoogleformTimeTrigger`? Or have they not been run yet?

2024-10-16 18:22 UTC, Reltre approved these changes

2024-10-16 21:48 UTC, ExperimentsInHonesty commented on dev-docs/app-scripts.md
> +- The time trigger turn google form AcceptingResponses feature on/off according to on and off time from the table
```suggestion
- The time trigger turns google form AcceptingResponses feature on/off according to on and off time from the table
```

2024-10-16 21:50 UTC, ExperimentsInHonesty commented on dev-docs/app-scripts.md
> +- The script weed out past events and only create triggers for 3( google has limit of 20 trigger per script) closest future events
```suggestion
- The script weeds out past events and only creates triggers for the 3 closest future events.  Google limits to no more than 20 triggers per script
```

2024-10-16 21:50 UTC, ExperimentsInHonesty commented on dev-docs/app-scripts.md
> +  - New edit trigger : call the script every time the event time is editted
```suggestion
  - New edit trigger: calls the script every time the event time is editted
```

2024-10-16 21:51 UTC, ExperimentsInHonesty commented on dev-docs/app-scripts.md
> +  - weekly update trigger : call the script every week (Monday 1AM) to update the trigger
```suggestion
  - weekly update trigger: calls the script every week (Monday at 1AM) to update the trigger
```

2024-10-16 21:53 UTC, ExperimentsInHonesty commented on dev-docs/app-scripts.md
> +  - weekly clear trigger : clear all triggers before weekly update
```suggestion
  - weekly clear trigger: clears all triggers before weekly update, in order to prevent exceeding the 20 trigger limit
```

2024-10-16 21:54 UTC, ExperimentsInHonesty commented on dev-docs/app-scripts.md
> +- same as GoogleformTimeTrigger beside turn 2 form AcceptingResponses feature on/off
```suggestion
- same functions as GoogleformTimeTrigger and also allows for a second form AcceptingResponses feature on/off
```

2024-10-16 21:56 UTC, ExperimentsInHonesty requested changes
See my suggested changes

2024-10-16 21:57 UTC, ExperimentsInHonesty commented on dev-docs/app-scripts.md
> +- To Run on Appscript Run the funtion "Run"
```suggestion
- To Run on Appscript execute the funtion "Run"
```

2024-10-16 21:58 UTC, ExperimentsInHonesty commented on dev-docs/app-scripts.md
> +- The script go over the all the drives listed and generate each users' permission role in to a CSV file named 'google_drive_permissions_audit.csv'
```suggestion
- The script runs though all the drives listed and generates a CSV (created date + 'google_drive_permissions_audit.csv') with each users' permission details 
```

2024-10-16 22:02 UTC, ExperimentsInHonesty commented on dev-docs/app-scripts.md
> +- The script log driveID that does not have permission to open in execution log
```suggestion
- If tables@hackforla.org does not have permission to access the drive, the drive ID will appear in the execution log with the text "list permission to Drive with driveID: "+driveID+ " fails " (where +driveID+ is replaced with the drive ID
```

2024-10-16 22:03 UTC, ExperimentsInHonesty requested changes
review other changes I just made

2024-10-23 20:47 UTC, merged